# Generated by Django 5.2.4 on 2025-08-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shelter_images/')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.shelter')),
            ],
        ),
    ]
