# Generated by Django 5.2.4 on 2025-07-16 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shelter',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_type',
            field=models.CharField(default='community', max_length=50),
        ),
        migrations.AddField(
            model_name='shelter',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
